#!/usr/bin/env bash

set -e
set -x

if rg "FIXME" --hidden --glob="!$0" "$PWD"; then
  echo "pre-push hook failed: FIXME not allowed"
  exit 1
fi
export RUSTFLAGS="-D warnings"
cargo clippy --all-targets --all-features
cargo test --all-features
glab ci lint

exit 0
