stages:
  - check
  - test

variables:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"
  CARGO_HOME: "${CI_PROJECT_DIR}/.cargo"
  RUSTUP_HOME: "${CI_PROJECT_DIR}/.rustup"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - target/
    - .cargo/
    - .rustup/

check:
  stage: check
  image: rust:1.89
  before_script:
    - rustup default stable
    - rustup component add clippy
  script:
    - cargo clippy --all-features

test:
  stage: test
  image: rust:1.89
  script:
    - cargo test --all-features
